### ISSUE TITLE
Barcelona.json

### ISSUE THREAD

**Issue by Jyojha** [natzar/European-Neighborhoods-Json-Coords#1]
Hi,

Just FYI, there is a minor issue. While parsing, the file Barcelona.json fails because of an extra comma right before the closing square bracket. The file works like a charm once the comma is removed. It is good data.

Thanks!

**Comment by natzar** [comment]
Ok!, thank you!

2017-01-23 1:39 GMT+01:00 Jyojha <notifications@github.com>:
